### ISSUE TITLE
MISP AMI Found!

### ISSUE THREAD

**Issue by d0s1nt** [MISP/misp-cloud#13]
As per other issues, there has been problems finding the MISP AMI in 'Community AMIs'. It's due to the user's AWS region which should be added to the installation guide.
region=eu-west-2 community AMIs:
MISP-1566311083 - ami-0cf7d0eb55274dba9
LumisPortal.10.0.0-fb113d11-1479-4158-9059-2336f05a1a5c-ami-ace50eba.3 - ami-10a7ad74

region=eu-east-2 community AMIs:
LumisPortal.10.0.0-fb113d11-1479-4158-9059-2336f05a1a5c-ami-ace50eba.3 - ami-10a7ad74

Hope it helps.

**Comment by 0xtf** [comment]
AMI's are region specific, that's why we list the AMI identifier and the region in which the AMI resides. 

By searching for "MISP" you'll find the results you mentioned, which is not unique to MISP _(because of Lu**misP**ortal)_. 

Next build the name of the image will be changed to MISP-CLOUD-$RANDOM, so that if someone searches for MISP-CLOUD our result will be the only one that pops up.

I'll keep this open until I push out another build. 

Thank you.

**Comment by 0xtf** [comment]
Images are now built with "MISP-Cloud-$TIMESTAMP". Searching for MISP still displays two results (as I explained before) but searching for "MISP-Cloud" only shows our images. 

![Screenshot 2019-08-31 at 21 13 19](https://user-images.githubusercontent.com/24301448/64068796-2eae0400-cc35-11e9-8dc3-554cef7dfbe8.png)
