### ISSUE TITLE
AWS marketplace - "Production usage is considered harmful"

### ISSUE THREAD

**Issue by adulau** [MISP/misp-cloud#17]
We received the following mail via the mailing-list. @0xtf could you have a look? Thanks a lot.

~~~
Dear Team,
 I would like to ask on MISP instance that is available in AWS marketplace – MISP-cloud.
After deployment it says: “Production usage is considered harmful.” Is it meant in general? Or if I would follow guidance in https://github.com/MISP/misp-cloud/wiki/MISP-and-Cloud-Securityand change salt and those passwords it can be used for production without any security problems?
Thank you for answer.
~~~

**Comment by 0xtf** [comment]
Hey @adulau,

Mind forwarding to the list? It's easier than me finding the thread ;)  

The message is displayed as soon as the instance is booted because all the login information, as well as DB information, are present in the project page. We wrote the document that the user referenced ([this one](https://github.com/MISP/misp-cloud/wiki/MISP-and-Cloud-Security)) to address what we consider to be good practices for usage of MISP-Cloud in production. So, in short, if the user follows the document that was referenced, I don't see any reason why it shouldn't be used in production. 

As for the message, it's just a matter of removing it in the MISP settings.
